name: youtube_downloader
description: "YT Downloader using YTDLP."

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  bitsdojo_window: ^0.1.6

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/fonts/inter/
    - assets/fonts/outfit/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf

        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500

        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
    - family: Outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Bold.ttf
          weight: 700
